<div class="container login-container">
    <?php
        $form = $this->loginForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/login'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        $form->setAttribute('class', 'login-form');
    ?>
    <h2 class="form-signin-heading">Login to <?=$this->config()['myapp']['name']?></h2>
    <?php echo $this->partial('_form.phtml', ['form' => $form, 'redirect'=>$this->redirect]); ?>

    <?php if ($this->enableRegistration) : ?>
    <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
    <?php endif; ?>
</div>