<section id="hero">
    <!--video poster="https://d2oovtgy70p1hm.cloudfront.net/assets/glowforge-hero-bg-74b96db4a079ac972b5ea945bf7e9dd47e077f2c780f41b5844bed55185a748c.jpg" autoplay="autoplay" loop="loop" class="hero-video">
        <source src="https://fat.gfycat.com/UnripeInsidiousJapanesebeetle.mp4"><source src="https://fat.gfycat.com/UnripeInsidiousJapanesebeetle.webm">
    </video-->
    <!--div class="hero-content">
        <h1 class="title text_headline-bold">
            Glowforge<sup>™</sup>
        </h1>
        <p class="subtitle text_headline-fine">
            The iconic 3D Laser Printer
        </p>
        <p class="subtitle text_headline-fine">
            Make magical things at the push of a button.
        </p>
        <div class="video-button">
            <a class="button button_red-medium button_shadow button_hover-lighten video-button-link" data-toggle="lightbox" data-modal-id="heroVideo" href="https://www.youtube.com/watch?v=ysCaqh38JVQ"><img class="icon-play-button" src="https://d2oovtgy70p1hm.cloudfront.net/assets/svg/play-button-c58c059c2218d093cc0290fb875f9a3e191db8aa212219d7fc249824cf2e9022.svg" alt="Play button">See how it works</a>
        </div>
    </div-->
</section>