<section id="hero">
    <!--video poster="" autoplay="autoplay" loop="loop" class="hero-video">
        <source src=""><source src="">
    </video-->
    <!--div class="hero-content">
        <h1 class="title text_headline-bold">
            Glowforge<sup>™</sup>
        </h1>
        <p class="subtitle text_headline-fine">
            The iconic 3D Laser Printer
        </p>
        <p class="subtitle text_headline-fine">
            Make magical things at the push of a button.
        </p>
        <div class="video-button">
            <a class="button button_red-medium button_shadow button_hover-lighten video-button-link" data-toggle="lightbox" data-modal-id="heroVideo" href=""><img class="icon-play-button" src="" alt="Play button">See how it works</a>
        </div>
    </div-->
</section>