<?php

if(!$this->size){
    $this->size = 'fa-lg';
}

if(!$this->facebook){
    $this->facebook = $this->config()['myapp']['social']['facebook'];
}

if(!$this->twitter){
    $this->twitter = $this->config()['myapp']['social']['twitter'];
}

if(!$this->linkedin){
    $this->linkedin = $this->config()['myapp']['social']['linkedin'];
}

if(!$this->youtube){
    $this->youtube = $this->config()['myapp']['social']['youtube'];
}

?>
<div class="social">
    <ul>
        <?php if($this->facebook): ?>
        <li>
            <a href="<?=$this->facebook?>" target="_blank">
                <i class="fa fa-facebook <?=$this->size?>"></i>
            </a>
         </li>
        <?php endif; ?>
        <?php if($this->linkedin): ?>
            <li>
                <a href="<?=$this->linkedin?>" target="_blank">
                    <i class="fa fa-linkedin <?=$this->size?>"></i>
                </a>
            </li>
        <?php endif; ?>
        <?php if($this->twitter): ?>
        <li>
            <a href="<?=$this->twitter?>" target="_blank">
                <i class="fa fa-twitter <?=$this->size?>"></i>
            </a>
        </li>
        <?php endif; ?>
        <?php if($this->youtube): ?>
        <li>
            <a href="<?=$this->youtube?>" target="_blank">
                <i class="fa fa-youtube <?=$this->size?>"></i>
            </a>
        </li>
        <?php endif; ?>
    </ul>
</div>