<div class="social">
    <ul>
        <li>
            <a href="https://www.facebook.com/pages/Vulcan-Systems/556615251088473" target="_blank">
                <i class="fa fa-facebook fa-lg"></i>
            </a>
        </li>
        <li>
            <a href="https://twitter.com/vulcansystems" target="_blank">
                <i class="fa fa-twitter fa-lg"></i>
            </a>
        </li>
        <li>
            <a href="https://www.linkedin.com/company/vulcansystems" target="_blank">
                <i class="fa fa-linkedin fa-lg"></i>
            </a>
        </li>
        <li>
            <a href="https://www.youtube.com/channel/UCCh9Frvp9O_NJvUcJZ_fcmw" target="_blank">
                <i class="fa fa-youtube fa-lg"></i>
            </a>
        </li>
    </ul>
</div>